[package]
name = "discover_plugin"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
tokio = { version = "1.47", features = ["full"] }
bevy = { version = "0.16", default-features = false }
sender_plugin = { path = "../../base/sender_plugin" }
